// Création d'un tableau vide
const fruits = [];
//const fruits2=new Array();
// Inserer des données à la fin du tableau
// push (element): retourne la nouvelle taille du tableau apres l'insertion
fruits.push("Pomme");
fruits.push("Banane");
fruits.push("Orange");

// Création et initialisation
const noms = ["Christian", "Steven", "Maeva", "Jordan", "Morgane"];
noms.push("Zakaria");
noms.push("Ludovic");
noms.push("Marion");
noms.push("Anouar");

console.log("Noms : ", noms);
console.log("Fruits : ", fruits);

// Acces
fruits[0]; //Pomme
fruits[2]; //Orange
noms[1]; //Steven
noms[4]; //Morgane